global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8889']
    scrape_interval: 10s
    metrics_path: /metrics

  - job_name: 'order-service-otel'
    static_configs:
      - targets: ['host.docker.internal:5000']
    scrape_interval: 10s
    metrics_path: /metrics

  - job_name: 'jaeger'
    static_configs:
      - targets: ['jaeger:14269']
